### ISSUE TITLE
训练代码

### ISSUE THREAD

**Issue by EricDengbowen** [GrassBro/OCOR#2]
作者你好，请问dist_train.sh或者训练代码在哪里~谢谢

**Comment by GrassBro** [comment]
@EricDengbowen 您好，已更新到tools文件夹

**Comment by EricDengbowen** [comment]
@GrassBro 作者你好，我还有其他两个问题，（1）inference的时候，模型config和pre_trained weights不匹配，如下所示。 （2）测试的时候，只看到了SOR的代码，并没有SA-SOR的代码，这在你们模型中是如何配置的呢？ （3）可以开放irsr数据集的generated maps么？

size mismatch for roi_head.bbox_head.0.sel_att.conv_q.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.0.sel_att.conv_k.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.0.sel_att.conv_v.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.0.sel_att.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
size mismatch for roi_head.bbox_head.0.sel_att.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.0.sel_att.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.1.sel_att.conv_q.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.1.sel_att.conv_k.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.1.sel_att.conv_v.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.1.sel_att.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
size mismatch for roi_head.bbox_head.1.sel_att.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.1.sel_att.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.2.sel_att.conv_q.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.2.sel_att.conv_k.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.2.sel_att.conv_v.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.2.sel_att.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
size mismatch for roi_head.bbox_head.2.sel_att.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.2.sel_att.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.3.sel_att.conv_q.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.3.sel_att.conv_k.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.3.sel_att.conv_v.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.3.sel_att.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
size mismatch for roi_head.bbox_head.3.sel_att.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.3.sel_att.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.4.sel_att.conv_q.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.4.sel_att.conv_k.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.4.sel_att.conv_v.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.4.sel_att.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
size mismatch for roi_head.bbox_head.4.sel_att.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.4.sel_att.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.5.sel_att.conv_q.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.5.sel_att.conv_k.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.5.sel_att.conv_v.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([2048, 512, 3, 3]).
size mismatch for roi_head.bbox_head.5.sel_att.conv.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
size mismatch for roi_head.bbox_head.5.sel_att.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for roi_head.bbox_head.5.sel_att.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2048]).
D:\Projects\OCOR\mmdet\apis\inference.py:47: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '

**Comment by GrassBro** [comment]
@EricDengbowen （1）pretrained weight中ocor模块中head是1，而源代码是4，现已修改为1。（2） 可以参考irsr原论文。（3）我手头暂时没有gpu重新训练，抱歉。

**Comment by EricDengbowen** [comment]
@GrassBro 作者你好，感谢你的回复，请问验证代码中，threshold设置为了0.28，这个threshold只是针对于ASSR dataset么？还是说IRSR dataset的threshold也是0.28，如果不是的话，请问IRSR 的threshold是多少？

            if result[0][i][j][4] > 0.28:
                mask = result[1][i][j]
                score = result[0][i][j][4]
                black_img[mask] = gray_colors[i]
                color_img[mask] = colors[i]

**Comment by GrassBro** [comment]
@EricDengbowen 不同机器，不同epoch，结果有一点随机性，无论irsr还是assr，threshold可以尝试从0.25到0.35调试。

**Comment by EricDengbowen** [comment]
@GrassBro 感谢您的回复。在配置文件queryinst_r50_fpn_1x_coco.py中，我看到了您num_classes=5，如下。根据result的结果，请问这个5是设置成每个数据集最大的instance 数量么？如果是irsr数据集的话，这个值是不是应该设置成最大instance 数量=8呢？感谢~
 bbox_head=[
            dict(
                type='DIIHead',
                num_classes=5,

**Comment by GrassBro** [comment]
@EricDengbowen 是这样的，注意一下irsr的label格式。

**Comment by GrassBro** [comment]
@EricDengbowen 是这样的，注意一下irsr的label格式。

**Comment by GrassBro** [comment]
@EricDengbowen 是这样的，注意一下irsr的label格式。

**Comment by GrassBro** [comment]
@EricDengbowen 是这样的，注意一下irsr的label格式。

**Comment by GrassBro** [comment]
@EricDengbowen 是这样的，注意一下irsr的label格式。

**Comment by EricDengbowen** [comment]
@GrassBro 作者你好，使用你的inference代码和pretrained model，在ASSR数据集中，测出的SOR指标和文章中提到的差不多，0.8843，但是用多种方法测算的SASOR指标相差较大，最好为0.64左右。可否在inference中加入评估SA-SOR指标的代码以便验证？感谢

**Comment by ChenShu1999** [comment]
@EricDengbowen 不好意思打扰您一下，原论文中提到使用pair-wise ranking loss来训练排序头，但是我在代码中并没有找到，请问您知道代码在哪一部分吗？以及关于SA-SOR指标的结果问题您解决了吗？

**Comment by Wu-ZJ** [comment]
> @EricDengbowen 不好意思打扰您一下，原论文中提到使用pair-wise ranking loss来训练排序头，但是我在代码中并没有找到，请问您知道代码在哪一部分吗？以及关于SA-SOR指标的结果问题您解决了吗？

请问你找到了嘛？以及论文中的ocor module您知道在哪嘛？

**Comment by ChenShu1999** [comment]
> > @EricDengbowen 不好意思打扰您一下，原论文中提到使用pair-wise ranking loss来训练排序头，但是我在代码中并没有找到，请问您知道代码在哪一部分吗？以及关于SA-SOR指标的结果问题您解决了吗？
> 
> 请问你找到了嘛？以及论文中的ocor module您知道在哪嘛？
pair-wise ranking loss还是没找到，ocor module在 mmdet/models/roi_heads/bbox_heads/OCOR.py

**Comment by EricDengbowen** [comment]
@ChenShu1999 @manguoooneil 没有找到loss的位置，SASOR指标我做了很多实验，用标准的IRSR的方法来做的话，分数更低，直接用暴力的pregenerated saliency map来测算的话不标准，但是会高一些，但也只是在0.6左右

**Comment by Wu-ZJ** [comment]
> 

请问用标准的IRSR方法来测，您测的SA-SOR指标是多少？

**Comment by ChenShu1999** [comment]
> @ChenShu1999 @manguoooneil 没有找到loss的位置，SASOR指标我做了很多实验，用标准的IRSR的方法来做的话，分数更低，直接用暴力的pregenerated saliency map来测算的话不标准，但是会高一些，但也只是在0.6左右

我没有自己训练，直接用提供的结果显著图测算的指标，MAE：0.079，SOR：0.85，SA-SOR:0.57，其中SA-SOR使用的是IRSR提供的代码，也是一直出不来。
现有使用的损失看上去只对检测和分割进行了处理，因为我目前没有找到排序损失，感觉可能是这里出的问题，所以两个排序指标都没有论文中的效果好。

**Comment by EricDengbowen** [comment]
@ChenShu1999 @manguoooneil 标准的IRSR方法来测算SA-SOR方法的话，在ASSR数据集中，我的SA-SOR结果和 @ChenShu1999 的几乎一致。但这是souce code+pretrained model，即使现在这里没有排序损失，也应该不会影响之前的pretrained model，所以也只能这样了，等待作者回复吧。

**Comment by ChenShu1999** [comment]
> @ChenShu1999 @manguoooneil 标准的IRSR方法来测算SA-SOR方法的话，在ASSR数据集中，我的SA-SOR结果和 @ChenShu1999 的几乎一致。但这是souce code+pretrained model，即使现在这里没有排序损失，也应该不会影响之前的pretrained model，所以也只能这样了，等待作者回复吧。

确实，给作者发了邮件，只能耐心等回复了。

**Comment by GrassBro** [comment]
@EricDengbowen ，是存在这样的指标偏低的问题的，0.6+也是合理的。现在评价标准有这样一个问题，无论是sa-sor还是sor，都会忽略一部分图片不计算指标，即他们提到的images not used，这类图片的范围就是结果波动的一大因素。

**Comment by GrassBro** [comment]
> > @ChenShu1999 @manguoooneil 没有找到loss的位置，SASOR指标我做了很多实验，用标准的IRSR的方法来做的话，分数更低，直接用暴力的pregenerated saliency map来测算的话不标准，但是会高一些，但也只是在0.6左右
> 
> 我没有自己训练，直接用提供的结果显著图测算的指标，MAE：0.079，SOR：0.85，SA-SOR:0.57，其中SA-SOR使用的是IRSR提供的代码，也是一直出不来。 现有使用的损失看上去只对检测和分割进行了处理，因为我目前没有找到排序损失，感觉可能是这里出的问题，所以两个排序指标都没有论文中的效果好。

@ChenShu1999 除了损失函数会带来影响，也可以关注mm最新的saliency ranking文章，Partitioned Saliency Ranking with Dense Pyramid Transformers，我看他们的ranking by partition带来的效果影响，更加直观。

**Comment by Wu-ZJ** [comment]
> > > @ChenShu1999 @manguoooneil 没有找到loss的位置，SASOR指标我做了很多实验，用标准的IRSR的方法来做的话，分数更低，直接用暴力的pregenerated saliency map来测算的话不标准，但是会高一些，但也只是在0.6左右
> > 
> > 
> > 我没有自己训练，直接用提供的结果显著图测算的指标，MAE：0.079，SOR：0.85，SA-SOR:0.57，其中SA-SOR使用的是IRSR提供的代码，也是一直出不来。 现有使用的损失看上去只对检测和分割进行了处理，因为我目前没有找到排序损失，感觉可能是这里出的问题，所以两个排序指标都没有论文中的效果好。
> 
> @ChenShu1999 除了损失函数会带来影响，也可以关注mm最新的saliency ranking文章，Partitioned Saliency Ranking with Dense Pyramid Transformers，我看他们的ranking by partition带来的效果影响，更加直观。

作者您好，另一个想问您的问题是，关于sor与sa-sor指标测评时，有一个阈值参数，会影响匹配精度，请问您在测试时这两个阈值设置的是多少？因为我看Partitioned Saliency Ranking with Dense Pyramid Transformers这篇文章目前的开源代码中，两个阈值分别给的0.98与0.1，而源论文的阈值都是0.5，这个阈值对最终结果影响非常大。

**Comment by qduOliver** [comment]
> @GrassBro 作者你好，使用你的inference代码和pretrained model，在ASSR数据集中，测出的SOR指标和文章中提到的差不多，0.8843，但是用多种方法测算的SASOR指标相差较大，最好为0.64左右。可否在inference中加入评估SA-SOR指标的代码以便验证？感谢

我同样使用IRSR的SA_SOR指标测试ASSR数据集，最高还没到0.6呢，是我本身机器或者环境的问题还是本身给的模型有问题，使用原始的模型和权重。
