### ISSUE TITLE
saliency ranking loss

### ISSUE THREAD

**Issue by ChenShu1999** [GrassBro/OCOR#3]
作者您好，论文中提到使用pair-wise ranking loss来训练排序头，但是我在代码中并没有找到，烦请您告知位置。

**Comment by GrassBro** [comment]
这个版本的代码没有包含这个loss，可以参考，https://github.com/dragonlee258079/Saliency-Ranking/blob/b98ecabfbba9030c4fdd3c8d60470f9377a4f937/detectron2/modeling/relation_head/loss.py#L4

**Comment by ChenShu1999** [comment]
感谢您的回复。另外我使用已提供的结果显著图测算的指标，MAE：0.079，SOR：0.85，SA-SOR：0.57，其中SA-SOR使用的是IRSR提供的代码（IOU阈值设置为0.5），结果与论文中给出的结果差别较大，不知道是不是我写的代码有问题，请问您能否补充SA-SOR的代码。

> 这个版本的代码没有包含这个loss，可以参考，https://github.com/dragonlee258079/Saliency-Ranking/blob/b98ecabfbba9030c4fdd3c8d60470f9377a4f937/detectron2/modeling/relation_head/loss.py#L4

**Comment by GrassBro** [comment]
> 

你的测试结果应该是合理的，可以尝试重新训练模型，找到一个images not used大一些，但是指标会高一些结果，存在一定的随机因素。也可以直接用现有的结果进行比较吧。此外，我也在想办法能不能找到一个更加充分的指标来进行评测。

**Comment by GrassBro** [comment]
> 感谢您的回复。另外我使用已提供的结果显著图测算的指标，MAE：0.079，SOR：0.85，SA-SOR：0.57，其中SA-SOR使用的是IRSR提供的代码（IOU阈值设置为0.5），结果与论文中给出的结果差别较大，不知道是不是我写的代码有问题，请问您能否补充SA-SOR的代码。
> 
> > 这个版本的代码没有包含这个loss，可以参考，https://github.com/dragonlee258079/Saliency-Ranking/blob/b98ecabfbba9030c4fdd3c8d60470f9377a4f937/detectron2/modeling/relation_head/loss.py#L4


你的测试结果应该是合理的，可以尝试重新训练模型，找到一个images not used大一些，但是指标会高一些结果，存在一定的随机因素。也可以直接用现有的结果进行比较吧。此外，我也在想办法能不能找到一个更加充分的指标来进行评测。
