### ISSUE TITLE
ocor module以及saliency ranking loss

### ISSUE THREAD

**Issue by Wu-ZJ** [GrassBro/OCOR#4]
作者你好，在看您的代码时，我没有找到您论文中提到的ocor module以及训练中用到的saliency ranking loss，请问可以告知在哪嘛？

**Comment by GrassBro** [comment]
你好，这个版本的代码没有包括saliency ranking loss。loss 你可以参考https://github.com/dragonlee258079/Saliency-Ranking/blob/b98ecabfbba9030c4fdd3c8d60470f9377a4f937/detectron2/modeling/relation_head/loss.py#L4
